import { ResourceType, TaskDifficulty, TaskPriority, TaskType } from "@prisma/client";

export interface SeedTask {
  code: string;
  title: string;
  description: string;
  type: TaskType;
  priority: TaskPriority;
  difficulty: TaskDifficulty;
  points: number;
  estimatedHours: number;
  instructions: string;
  acceptanceCriteria: string[];
  isWeeklyProject?: boolean;
}

export interface SeedResource {
  title: string;
  description: string;
  url: string;
  type: ResourceType;
  isRequired: boolean;
  estimatedMinutes: number;
  topic?: string;
}

export interface SeedWeek {
  weekNumber: number;
  title: string;
  description: string;
  objectives: string[];
  topics: string[];
  resources: SeedResource[];
  tasks: SeedTask[];
  researchQuestions: string[];
  weeklyProjectTitle: string;
  weeklyProjectDescription: string;
  submissionRequirements: string[];
}

const DOC = ResourceType.DOCUMENTATION;

export const weeksData: SeedWeek[] = [
  {
    weekNumber: 1,
    title: "JavaScript Fundamentals",
    description: "Build a solid foundation in core JavaScript: variables, types, control flow, functions, arrays and objects.",
    objectives: [
      "Understand variables, data types and operators",
      "Write conditional logic and loops confidently",
      "Define and call functions, including arrow functions",
      "Manipulate arrays and objects",
      "Understand scope and hoisting",
    ],
    topics: [
      "Programming Fundamentals",
      "Variables",
      "Data Types",
      "Operators",
      "Conditions",
      "Loops",
      "Functions",
      "Arrays",
      "Objects",
      "Scope",
    ],
    resources: [
      {
        title: "MDN — JavaScript Guide",
        description: "The canonical guide to core JavaScript concepts.",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 120,
        topic: "Programming Fundamentals",
      },
      {
        title: "MDN — Arrays",
        description: "Reference for array creation and manipulation.",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Indexed_collections",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 45,
        topic: "Arrays",
      },
      {
        title: "MDN — Functions",
        description: "Everything about declaring and using functions in JavaScript.",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions",
        type: DOC,
        isRequired: false,
        estimatedMinutes: 40,
        topic: "Functions",
      },
    ],
    tasks: [
      {
        code: "JS-001",
        title: "Positive / Negative / Zero",
        description: "Write a function that classifies a number as positive, negative or zero.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Write `classifyNumber(n)` that returns 'positive', 'negative' or 'zero'. Cover edge cases like -0 and NaN.",
        acceptanceCriteria: [
          "Returns 'positive' for numbers > 0",
          "Returns 'negative' for numbers < 0",
          "Returns 'zero' for 0",
          "Includes at least 3 test cases run manually or with a test runner",
        ],
      },
      {
        code: "JS-002",
        title: "Grade Calculator",
        description: "Convert a numeric score into a letter grade.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Write `getGrade(score)` returning 'A'/'B'/'C'/'D'/'F' using standard thresholds (90/80/70/60).",
        acceptanceCriteria: ["Handles boundary values correctly", "Throws or handles invalid input (score < 0 or > 100)"],
      },
      {
        code: "JS-003",
        title: "Array Statistics",
        description: "Compute basic statistics (min, max, sum, average) over an array of numbers.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 8,
        estimatedHours: 1,
        instructions: "Write `getStats(numbers)` returning `{ min, max, sum, average }` without using built-in Math.min/max spread on huge arrays incorrectly.",
        acceptanceCriteria: ["Works for empty arrays (documented behavior)", "average is rounded to 2 decimals"],
      },
      {
        code: "JS-004",
        title: "Employee Salary Calculator",
        description: "Calculate net salary from a list of employees with base pay, bonus and deductions.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Given an array of employee objects `{ name, base, bonus, deductions }`, compute `netSalary` for each and the total payroll.",
        acceptanceCriteria: ["Returns a new array, does not mutate input", "Total payroll matches the sum of net salaries"],
      },
      {
        code: "JS-005",
        title: "Value Frequency Counter",
        description: "Count how many times each value appears in an array.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 8,
        estimatedHours: 1,
        instructions: "Write `countFrequency(arr)` returning an object mapping each distinct value to its occurrence count.",
        acceptanceCriteria: ["Works with strings and numbers", "Order of keys does not matter"],
      },
      {
        code: "PS-001",
        title: "Reverse a String",
        description: "Classic problem-solving warm-up.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Implement `reverseString(str)` without using `.reverse()`. Push your solution to a public GitHub repo.",
        acceptanceCriteria: ["Handles empty string", "Handles unicode/multi-byte characters reasonably", "Solution pushed to GitHub"],
      },
      {
        code: "PS-002",
        title: "Palindrome Check",
        description: "Determine whether a string reads the same forwards and backwards.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Implement `isPalindrome(str)`, ignoring case and non-alphanumeric characters.",
        acceptanceCriteria: ["'A man a plan a canal Panama' returns true", "Solution pushed to GitHub"],
      },
      {
        code: "JS-006",
        title: "Weekly Project: Student Management System",
        description: "A CLI or browser-console based system for managing students and grades.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 6,
        instructions:
          "Build a Student Management System covering: Add Student, Update Student, Delete Student, Find Student, List Students, Calculate Average, Highest Grade, Failed Students. Use plain JavaScript (arrays/objects), no frameworks.",
        acceptanceCriteria: [
          "All 8 required operations implemented and demonstrated",
          "Data stored in an in-memory array of student objects",
          "Code is pushed to a public GitHub repository with a README explaining usage",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["What is the difference between var, let and const?", "What is hoisting in JavaScript?"],
    weeklyProjectTitle: "Student Management System",
    weeklyProjectDescription:
      "A console-based system to add, update, delete, find and list students, and compute class average, highest grade and the list of failed students.",
    submissionRequirements: ["Public GitHub repository URL", "README with setup/run instructions"],
  },
  {
    weekNumber: 2,
    title: "Modern JavaScript",
    description: "Level up with ES6+ array methods, destructuring, modules, async programming and the Fetch API.",
    objectives: [
      "Use map/filter/find/some/every/reduce/sort fluently",
      "Apply destructuring, spread/rest, optional chaining and nullish coalescing",
      "Understand Promises, async/await and the event loop",
      "Fetch and handle JSON data from an API",
    ],
    topics: [
      "Array Methods (map, filter, find, some, every, reduce, sort)",
      "Destructuring",
      "Spread & Rest",
      "Optional Chaining",
      "Nullish Coalescing",
      "Modules",
      "Error Handling",
      "Promises & async/await",
      "Fetch API",
      "JSON",
      "Event Loop",
    ],
    resources: [
      {
        title: "MDN — Array.prototype methods",
        description: "Reference for map, filter, reduce and friends.",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "Array Methods",
      },
      {
        title: "MDN — Using Promises",
        description: "How Promises and async/await work under the hood.",
        url: "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 45,
        topic: "Promises & async/await",
      },
      {
        title: "MDN — Fetch API",
        description: "Making HTTP requests from JavaScript.",
        url: "https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 30,
        topic: "Fetch API",
      },
    ],
    tasks: [
      {
        code: "JS-007",
        title: "Array Method Chains",
        description: "Transform a dataset using chained array methods.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Given an array of orders, use map/filter/reduce to compute total revenue per category.",
        acceptanceCriteria: ["No for-loops used", "Uses at least 3 different array methods"],
      },
      {
        code: "JS-008",
        title: "Destructuring & Spread Practice",
        description: "Refactor verbose object/array access into destructuring and spread syntax.",
        type: TaskType.CODING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.EASY,
        points: 6,
        estimatedHours: 0.75,
        instructions: "Refactor the provided snippet using destructuring, spread and optional chaining/nullish coalescing.",
        acceptanceCriteria: ["No unnecessary intermediate variables", "Uses optional chaining for nested access"],
      },
      {
        code: "JS-009",
        title: "Async/Await Data Loader",
        description: "Fetch data from a public API and handle loading/error/success states.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Write an async function that fetches from a public JSON API, with try/catch error handling and a timeout.",
        acceptanceCriteria: ["Handles network failure gracefully", "Uses async/await, not raw .then chains"],
      },
      {
        code: "PS-003",
        title: "Find Most Frequent Element",
        description: "Return the most frequently occurring element in an array.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.MEDIUM,
        points: 6,
        estimatedHours: 0.75,
        instructions: "Implement `findMostFrequent(arr)`. Break ties by first occurrence.",
        acceptanceCriteria: ["O(n) time complexity", "Solution pushed to GitHub"],
      },
      {
        code: "PS-004",
        title: "Flatten Nested Array",
        description: "Flatten an arbitrarily nested array.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.MEDIUM,
        points: 6,
        estimatedHours: 0.75,
        instructions: "Implement `flattenArray(arr)` without using `Array.prototype.flat`.",
        acceptanceCriteria: ["Works for arbitrary nesting depth", "Solution pushed to GitHub"],
      },
      {
        code: "JS-010",
        title: "Weekly Project: Product Explorer",
        description: "A small app that lists products fetched from an API with search, filter and sort.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 6,
        instructions:
          "Build Product Explorer: product list, product details, search, category filter, sorting, and explicit loading/error/empty states, using vanilla JS + Fetch.",
        acceptanceCriteria: [
          "Loading, error and empty states are all visibly handled",
          "Search and category filter both work against fetched data",
          "Code pushed to GitHub with a README",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["Explain the JavaScript Event Loop.", "Promise.all vs Promise.allSettled — when would you use each?"],
    weeklyProjectTitle: "Product Explorer",
    weeklyProjectDescription: "Products, product details, search, category filter, sorting, and loading/error/empty states.",
    submissionRequirements: ["Public GitHub repository URL", "Live demo URL (optional)"],
  },
  {
    weekNumber: 3,
    title: "Git & GitHub + TypeScript",
    description: "Learn professional version control workflows and add static typing to your JavaScript with TypeScript.",
    objectives: [
      "Use Git branches, commits and pull requests confidently",
      "Understand TypeScript's core type system",
      "Model data with interfaces, unions and generics",
      "Migrate a small JS project to TypeScript",
    ],
    topics: [
      "Git",
      "GitHub",
      "Branches",
      "Commits",
      "Merge",
      "Pull Requests",
      "TypeScript Primitives",
      "Arrays & Objects",
      "Functions",
      "type vs interface",
      "Union & Literal Types",
      "Generics",
      "unknown / any / void / never",
      "Modules",
    ],
    resources: [
      {
        title: "Git Documentation",
        description: "Official Git reference and guides.",
        url: "https://git-scm.com/doc",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "Git",
      },
      {
        title: "TypeScript Handbook",
        description: "The official TypeScript language handbook.",
        url: "https://www.typescriptlang.org/docs/handbook/intro.html",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 90,
        topic: "TypeScript",
      },
      {
        title: "GitHub Docs — About Pull Requests",
        description: "How pull requests and code review work on GitHub.",
        url: "https://docs.github.com/en/pull-requests",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 30,
        topic: "Pull Requests",
      },
    ],
    tasks: [
      {
        code: "GIT-001",
        title: "First Feature Branch & PR",
        description: "Practice the branch → commit → push → PR workflow.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.EASY,
        points: 8,
        estimatedHours: 1,
        instructions: "Create a repo, work on branch `feature/GIT-001-setup`, make at least 3 meaningful commits, and open a pull request into main.",
        acceptanceCriteria: ["Branch name follows convention", "PR description explains the change", "At least 3 commits with clear messages"],
      },
      {
        code: "TS-001",
        title: "Type a JavaScript Module",
        description: "Add TypeScript types to an existing untyped module.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Convert the provided .js file to .ts, adding interfaces/types for all function parameters and return values. Avoid `any`.",
        acceptanceCriteria: ["Compiles with strict mode, no errors", "No use of `any` unless justified in a comment"],
      },
      {
        code: "TS-002",
        title: "Generic Data Store",
        description: "Build a simple generic in-memory store.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.HARD,
        points: 12,
        estimatedHours: 2,
        instructions: "Implement a generic `Store<T>` class with add/remove/find/list methods, fully typed.",
        acceptanceCriteria: ["Store<T> works for at least two different types in a demo", "No `any` in the implementation"],
      },
      {
        code: "PS-005",
        title: "Remove Duplicates",
        description: "Remove duplicate values from an array while preserving order.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Implement `removeDuplicates<T>(arr: T[]): T[]` in TypeScript.",
        acceptanceCriteria: ["Order of first occurrence preserved", "Solution pushed to GitHub"],
      },
      {
        code: "TS-003",
        title: "Weekly Project: Task Management Application",
        description: "A typed task manager with local persistence.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 6,
        instructions:
          "Build a Task Management Application in TypeScript: create/edit/delete tasks, search, status, priority, filtering, persisted to LocalStorage. Developed on a feature branch and merged via pull request.",
        acceptanceCriteria: [
          "All CRUD operations implemented and typed",
          "State persists across page reloads via LocalStorage",
          "Developed via at least one feature branch + PR merged into main",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["Merge vs Rebase — what's the difference and when would you use each?", "When would you use `type` vs `interface` in TypeScript?"],
    weeklyProjectTitle: "Task Management Application",
    weeklyProjectDescription: "Create, edit, delete, search, filter by status/priority, and persist tasks to LocalStorage.",
    submissionRequirements: ["Public GitHub repository URL", "Pull request URL"],
  },
  {
    weekNumber: 4,
    title: "React Fundamentals",
    description: "Learn component-based UI development with React: props, state, events, and forms.",
    objectives: [
      "Build components with JSX, props and state",
      "Handle events and conditional/list rendering",
      "Manage forms and lift state between components",
      "Use useState and useEffect correctly",
    ],
    topics: [
      "Components",
      "JSX",
      "Props",
      "State",
      "Events",
      "Conditional Rendering",
      "Lists",
      "Forms",
      "useState",
      "useEffect",
      "Lifting State",
      "Reusable Components",
    ],
    resources: [
      {
        title: "React Documentation",
        description: "The official React documentation.",
        url: "https://react.dev/learn",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 120,
        topic: "Components",
      },
      {
        title: "React — Reacting to Input with State",
        description: "How to think about state in React.",
        url: "https://react.dev/learn/reacting-to-input-with-state",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 30,
        topic: "State",
      },
    ],
    tasks: [
      {
        code: "REACT-001",
        title: "Component Library Warm-up",
        description: "Build a handful of small reusable presentational components.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 8,
        estimatedHours: 1.5,
        instructions: "Build Button, Card and Badge components accepting props for variant/size/children.",
        acceptanceCriteria: ["Components accept and forward props correctly", "Rendered in a demo page with multiple variants"],
      },
      {
        code: "REACT-002",
        title: "Controlled Form",
        description: "Build a controlled form with validation feedback.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 2,
        instructions: "Build a signup form using useState for each field, with inline validation messages.",
        acceptanceCriteria: ["Form is fully controlled (no uncontrolled inputs)", "Submit is disabled until required fields are valid"],
      },
      {
        code: "REACT-003",
        title: "Data Fetching with useEffect",
        description: "Fetch and render a list with loading/error states using useEffect.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 2,
        instructions: "Fetch a list from a public API in useEffect, showing a loading skeleton and an error message on failure.",
        acceptanceCriteria: ["Cleans up properly if component unmounts mid-fetch", "Loading and error states are both visibly distinct"],
      },
      {
        code: "REACT-004",
        title: "Weekly Project: Course Management Frontend",
        description: "A multi-page React app for browsing courses and trainers.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 7,
        instructions:
          "Build a Course Management Frontend with pages: Login, Courses, Course Details, Trainers, Categories, My Registrations. Static/mock data is fine this week.",
        acceptanceCriteria: [
          "All 6 pages implemented as components",
          "Navigation between pages works",
          "Code pushed to GitHub",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["Props vs State — what's the difference and when do you use each?"],
    weeklyProjectTitle: "Course Management Frontend",
    weeklyProjectDescription: "Pages: Login, Courses, Course Details, Trainers, Categories, My Registrations.",
    submissionRequirements: ["Public GitHub repository URL", "Live demo URL (optional)"],
  },
  {
    weekNumber: 5,
    title: "Professional React",
    description: "Add routing, global state, data fetching and form validation to build production-grade React apps.",
    objectives: [
      "Set up React Router with layouts and protected routes",
      "Manage global state with Zustand and server state with TanStack Query",
      "Validate forms with React Hook Form + Zod",
      "Integrate a REST API with Axios, handling loading/error/empty/success states",
    ],
    topics: [
      "React Router",
      "Layouts",
      "Protected Routes",
      "Custom Hooks",
      "Context",
      "Zustand",
      "TanStack Query",
      "Axios",
      "React Hook Form",
      "Zod",
      "API Integration",
    ],
    resources: [
      {
        title: "React Router Documentation",
        description: "Official docs for React Router.",
        url: "https://reactrouter.com/en/main",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "React Router",
      },
      {
        title: "TanStack Query Documentation",
        description: "Official docs for TanStack Query.",
        url: "https://tanstack.com/query/latest/docs/framework/react/overview",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "TanStack Query",
      },
    ],
    tasks: [
      {
        code: "REACT-005",
        title: "Router & Protected Routes",
        description: "Add React Router with a layout and an auth-protected route.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Set up React Router with a shared layout (nav + outlet) and a ProtectedRoute wrapper that redirects unauthenticated users to /login.",
        acceptanceCriteria: ["Unauthenticated access to a protected route redirects to /login", "Layout renders consistently across pages"],
      },
      {
        code: "REACT-006",
        title: "Global State with Zustand",
        description: "Model auth/session state in a Zustand store.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 8,
        estimatedHours: 1,
        instructions: "Create a Zustand store holding the current user and token, with login/logout actions.",
        acceptanceCriteria: ["Store persists across page reload (e.g. via localStorage)", "logout() clears all session state"],
      },
      {
        code: "REACT-007",
        title: "Form Validation with RHF + Zod",
        description: "Rebuild the signup form using React Hook Form and Zod schema validation.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Replace manual useState validation with React Hook Form + a Zod resolver schema.",
        acceptanceCriteria: ["Validation errors come from a single Zod schema", "Submit handler receives fully typed, validated data"],
      },
      {
        code: "REACT-008",
        title: "Weekly Project: Connect to Mock REST API",
        description: "Wire the Course Management frontend up to a real mock REST API.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.HARD,
        points: 25,
        estimatedHours: 6,
        instructions:
          "Connect the Course Management frontend from week 4 to a mock REST API using Axios + TanStack Query. Handle loading, error, empty and success states everywhere, plus API and form validation.",
        acceptanceCriteria: [
          "Every data-fetching page handles loading/error/empty/success explicitly",
          "Mutations (create/update) use TanStack Query with cache invalidation",
          "Form submissions are validated both client-side and against API error responses",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["When should useEffect be used, and when should it be avoided?"],
    weeklyProjectTitle: "Course Management — API Integration",
    weeklyProjectDescription: "Connect the Course Management frontend to a mock REST API with full state handling and validation.",
    submissionRequirements: ["Public GitHub repository URL", "Live demo URL (optional)"],
  },
  {
    weekNumber: 6,
    title: "Node.js + Express",
    description: "Build backend REST APIs with Node.js and Express: routing, middleware, and request handling.",
    objectives: [
      "Understand Node.js modules, npm and environment variables",
      "Build Express routes, controllers and middleware",
      "Handle HTTP methods, status codes, params, query and body correctly",
    ],
    topics: [
      "Node.js",
      "npm & package.json",
      "Modules",
      "Environment Variables",
      "Async Programming",
      "Express Routes",
      "Controllers",
      "Middleware",
      "Request & Response",
      "HTTP Methods & Status Codes",
      "Params, Query, Body, Headers",
    ],
    resources: [
      {
        title: "Node.js Documentation",
        description: "Official Node.js API documentation.",
        url: "https://nodejs.org/en/docs",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "Node.js",
      },
      {
        title: "Express Documentation",
        description: "Official Express.js guide and API reference.",
        url: "https://expressjs.com/en/guide/routing.html",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 60,
        topic: "Express",
      },
    ],
    tasks: [
      {
        code: "NODE-001",
        title: "First Express Server",
        description: "Stand up a minimal Express server with a health check route.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 5,
        estimatedHours: 0.5,
        instructions: "Create an Express app with a GET /health route returning `{ status: 'ok' }` and environment variables loaded from .env.",
        acceptanceCriteria: [".env is used for PORT, not hardcoded", "Server logs the listening port on start"],
      },
      {
        code: "NODE-002",
        title: "Custom Middleware",
        description: "Write a request logging middleware.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 6,
        estimatedHours: 0.75,
        instructions: "Write middleware that logs method, path and response time for every request.",
        acceptanceCriteria: ["Applied globally via app.use", "Does not interfere with error responses"],
      },
      {
        code: "PS-006",
        title: "Calculate Cart Total",
        description: "Compute the total price of a shopping cart, including quantity and discounts.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.MEDIUM,
        points: 6,
        estimatedHours: 0.75,
        instructions: "Implement `calculateCartTotal(items)` where each item has price, quantity and an optional discountPercent.",
        acceptanceCriteria: ["Discounts applied per-item before summing", "Solution pushed to GitHub"],
      },
      {
        code: "NODE-003",
        title: "Weekly Project: Users REST API",
        description: "A CRUD REST API for managing users, backed by an in-memory array.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 6,
        instructions:
          "Build a Users REST API with GET /users, GET /users/:id, POST /users, PATCH /users/:id, DELETE /users/:id. Follow Route → Controller → Service layering. Validate input and return correct status codes.",
        acceptanceCriteria: [
          "All 5 endpoints implemented and manually tested (e.g. via Postman)",
          "400 returned for invalid input, 404 for missing users",
          "Business logic lives in a service layer, not in route handlers",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["What is middleware in Express, and how does the request/response cycle flow through it?"],
    weeklyProjectTitle: "Users REST API",
    weeklyProjectDescription: "GET/POST/PATCH/DELETE endpoints for managing users, following Route → Controller → Service architecture.",
    submissionRequirements: ["Public GitHub repository URL", "Postman collection or example requests in the README"],
  },
  {
    weekNumber: 7,
    title: "PostgreSQL + SQL",
    description: "Learn relational database design and SQL: tables, constraints, joins, aggregation and ERDs.",
    objectives: [
      "Design normalized relational tables with keys and constraints",
      "Write CRUD SQL queries plus filtering, sorting and pagination",
      "Use aggregation (COUNT/AVG/SUM/GROUP BY) and JOINs",
      "Design an ERD for a real domain",
    ],
    topics: [
      "Tables, Rows, Columns",
      "Primary & Foreign Keys",
      "Constraints",
      "CREATE / INSERT / SELECT / UPDATE / DELETE",
      "WHERE, LIKE, IN, ORDER BY, LIMIT, OFFSET",
      "COUNT, AVG, SUM, GROUP BY",
      "INNER JOIN, LEFT JOIN",
      "One-to-One, One-to-Many, Many-to-Many",
      "ERD",
    ],
    resources: [
      {
        title: "PostgreSQL Documentation",
        description: "Official PostgreSQL manual.",
        url: "https://www.postgresql.org/docs/current/",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 90,
        topic: "SQL",
      },
      {
        title: "PostgreSQL Tutorial — Joins",
        description: "How INNER JOIN, LEFT JOIN and friends work.",
        url: "https://www.postgresql.org/docs/current/queries-table-expressions.html",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 45,
        topic: "Joins",
      },
    ],
    tasks: [
      {
        code: "SQL-001",
        title: "Schema Creation",
        description: "Write CREATE TABLE statements for a small blog domain.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.EASY,
        points: 8,
        estimatedHours: 1,
        instructions: "Create `users` and `posts` tables with appropriate primary/foreign keys and NOT NULL constraints.",
        acceptanceCriteria: ["posts.user_id references users.id", "Appropriate columns are NOT NULL"],
      },
      {
        code: "SQL-002",
        title: "Filtering & Aggregation Queries",
        description: "Write queries using WHERE, ORDER BY, LIMIT and GROUP BY.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Write 5 queries: top 5 newest posts, posts per user (GROUP BY), average post length, posts matching a LIKE search, paginated results with LIMIT/OFFSET.",
        acceptanceCriteria: ["All 5 queries run successfully against seeded data", "Uses GROUP BY and an aggregate function correctly"],
      },
      {
        code: "SQL-003",
        title: "JOIN Practice",
        description: "Combine data across tables using INNER and LEFT JOIN.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Write a query listing every user with their post count, including users with zero posts (LEFT JOIN).",
        acceptanceCriteria: ["Users with 0 posts still appear with count 0", "Uses explicit JOIN syntax, not comma joins"],
      },
      {
        code: "SQL-004",
        title: "Weekly Project: Training Platform ERD",
        description: "Design the database for a Training Management Platform.",
        type: TaskType.PROJECT,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 25,
        estimatedHours: 5,
        instructions:
          "Design an ERD and CREATE TABLE statements for: users, courses, trainers, categories, registrations. Identify the relationship type (1:1, 1:N, M:N) for each pair.",
        acceptanceCriteria: [
          "ERD diagram included (image or tool link) in the repo",
          "All 5 tables created with correct keys and constraints",
          "Relationship types documented in the README",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["INNER JOIN vs LEFT JOIN — what's the difference, with an example?"],
    weeklyProjectTitle: "Training Platform Database Design",
    weeklyProjectDescription: "ERD and schema for users, courses, trainers, categories and registrations.",
    submissionRequirements: ["Public GitHub repository URL with .sql files", "ERD diagram"],
  },
  {
    weekNumber: 8,
    title: "Prisma + Authentication",
    description: "Model your database with Prisma ORM and add secure authentication and authorization.",
    objectives: [
      "Define Prisma schema models, relations and run migrations",
      "Perform CRUD through Prisma Client",
      "Hash passwords with bcrypt and issue JWTs",
      "Implement role-based authorization middleware",
    ],
    topics: ["Prisma Schema", "Models & Relations", "Migrations", "CRUD with Prisma", "bcrypt", "JWT", "Authentication", "Authorization", "RBAC"],
    resources: [
      {
        title: "Prisma Documentation",
        description: "Official Prisma ORM documentation.",
        url: "https://www.prisma.io/docs",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 90,
        topic: "Prisma",
      },
      {
        title: "MDN — JSON Web Tokens overview",
        description: "How JWTs are structured and used for stateless auth.",
        url: "https://developer.mozilla.org/en-US/docs/Web/Security",
        type: DOC,
        isRequired: false,
        estimatedMinutes: 20,
        topic: "JWT",
      },
    ],
    tasks: [
      {
        code: "PRISMA-001",
        title: "Model the Blog Schema in Prisma",
        description: "Translate week 7's SQL schema into a Prisma schema.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Write a Prisma schema for User and Post with a one-to-many relation, then run a migration.",
        acceptanceCriteria: ["`prisma migrate dev` runs cleanly", "Relation fields defined on both models"],
      },
      {
        code: "AUTH-001",
        title: "Password Hashing & Login Endpoint",
        description: "Implement a secure login endpoint.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 12,
        estimatedHours: 2,
        instructions: "Hash passwords with bcrypt on signup, and implement POST /login that verifies the password and returns a signed JWT.",
        acceptanceCriteria: ["Plaintext passwords are never stored", "Invalid credentials return 401, not 500"],
      },
      {
        code: "AUTH-002",
        title: "Role-Based Authorization Middleware",
        description: "Restrict a route to a specific role.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Write `authorize(...roles)` middleware and protect an admin-only route with it.",
        acceptanceCriteria: ["Requests without a valid token return 401", "Requests with the wrong role return 403"],
      },
      {
        code: "FS-001",
        title: "Weekly Project: Training Management REST API",
        description: "A full REST API covering Auth, Users, Courses, Trainers, Categories, Registrations.",
        type: TaskType.PROJECT,
        priority: TaskPriority.URGENT,
        difficulty: TaskDifficulty.HARD,
        points: 30,
        estimatedHours: 8,
        instructions:
          "Build a REST API with modules: Auth, Users, Courses, Trainers, Categories, Registrations, using Prisma + PostgreSQL, JWT auth and role-based authorization.",
        acceptanceCriteria: [
          "All 6 modules implemented with CRUD where applicable",
          "Auth required on all non-public routes, verified server-side",
          "Passwords hashed, JWTs signed with a secret from environment variables",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["Authentication vs Authorization — what's the difference?"],
    weeklyProjectTitle: "Training Management REST API",
    weeklyProjectDescription: "Auth, Users, Courses, Trainers, Categories and Registrations modules on Prisma + PostgreSQL.",
    submissionRequirements: ["Public GitHub repository URL", "Pull request URL", ".env.example included (no real secrets)"],
  },
  {
    weekNumber: 9,
    title: "Full-Stack Integration",
    description: "Connect the React frontend to the Express + Prisma backend end-to-end, handling real-world error cases.",
    objectives: [
      "Wire React + Axios to a real Express + Prisma API",
      "Implement end-to-end authentication and protected routes",
      "Handle 400/401/403/404/409/500 responses correctly on the client",
    ],
    topics: ["Full-Stack Auth Flow", "Courses", "Registrations", "Users & Roles", "Protected Routes", "Validation", "Error Handling", "HTTP Status Codes"],
    resources: [
      {
        title: "MDN — HTTP response status codes",
        description: "Reference for all standard HTTP status codes.",
        url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 30,
        topic: "HTTP Status Codes",
      },
    ],
    tasks: [
      {
        code: "FS-002",
        title: "End-to-End Login Flow",
        description: "Connect the React login form to the real backend.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Wire the login form to POST /api/auth/login, store the JWT, and redirect to the dashboard on success.",
        acceptanceCriteria: ["Invalid credentials show an inline error, not a crash", "Token is attached to subsequent Axios requests"],
      },
      {
        code: "FS-003",
        title: "Course Registration Flow",
        description: "Implement registering for a course end-to-end, including conflict handling.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.HARD,
        points: 15,
        estimatedHours: 2.5,
        instructions: "Implement course registration. The API must reject duplicate registrations (409) and full courses (400/409); the UI must surface both clearly.",
        acceptanceCriteria: ["Duplicate registration is rejected server-side, not just client-side", "UI shows a specific message for each rejection reason"],
      },
      {
        code: "PS-007",
        title: "Group Orders By User",
        description: "Transform a flat list of orders into orders grouped by user.",
        type: TaskType.PROBLEM_SOLVING,
        priority: TaskPriority.LOW,
        difficulty: TaskDifficulty.MEDIUM,
        points: 6,
        estimatedHours: 1,
        instructions: "Implement `groupOrdersByUser(orders)` returning a map of userId to their orders.",
        acceptanceCriteria: ["Each order appears under exactly one user", "Solution pushed to GitHub"],
      },
      {
        code: "FS-004",
        title: "Weekly Project: Full-Stack Course Platform",
        description: "Bring the frontend and backend together into one working application.",
        type: TaskType.PROJECT,
        priority: TaskPriority.URGENT,
        difficulty: TaskDifficulty.HARD,
        points: 30,
        estimatedHours: 8,
        instructions:
          "Connect React → Axios → Express → Prisma → PostgreSQL end-to-end for Authentication, Courses, Registrations, Users and Roles, with protected routes and full validation/error handling on both ends.",
        acceptanceCriteria: [
          "Login, course browsing and registration all work against the real API",
          "Client correctly handles 400/401/403/404/409/500 with distinct UI feedback",
          "Protected routes redirect unauthenticated users",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: ["How should a client application differentiate its handling of a 401 vs a 403 response?"],
    weeklyProjectTitle: "Full-Stack Course Platform",
    weeklyProjectDescription: "React + Axios + Express + Prisma + PostgreSQL, fully integrated with auth, roles and validation.",
    submissionRequirements: ["Public GitHub repository URL (frontend + backend)", "Live demo URL (optional)"],
  },
  {
    weekNumber: 10,
    title: "Professional Git Workflow",
    description: "Practice the branching, PR and code review workflow used by real engineering teams.",
    objectives: [
      "Work exclusively through feature branches and pull requests",
      "Write conventional commit messages",
      "Resolve merge conflicts",
      "Participate in code review as both author and reviewer",
    ],
    topics: ["Feature Branches", "Pull Requests", "Code Review", "Merge Conflicts", "Commit Conventions", "Team Development"],
    resources: [
      {
        title: "Conventional Commits",
        description: "A specification for adding human and machine readable meaning to commit messages.",
        url: "https://www.conventionalcommits.org/en/v1.0.0/",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 20,
        topic: "Commit Conventions",
      },
      {
        title: "GitHub Docs — Resolving a merge conflict",
        description: "Step-by-step guide to resolving conflicts on GitHub.",
        url: "https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 20,
        topic: "Merge Conflicts",
      },
    ],
    tasks: [
      {
        code: "GIT-003",
        title: "Ticket: feature/AUTH-001-login",
        description: "Simulated company ticket: implement the login screen on its own branch.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 2,
        instructions: "On branch `feature/AUTH-001-login`, implement the login screen. Commit using Conventional Commits (e.g. `feat: add login form`). Open a PR referencing AUTH-001.",
        acceptanceCriteria: ["Branch and commits follow the naming/convention rules", "PR is opened against main with a clear description"],
      },
      {
        code: "GIT-004",
        title: "Ticket: bugfix/REG-004-capacity",
        description: "Simulated company ticket: fix a course-capacity bug.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "On branch `bugfix/REG-004-capacity`, fix the bug that allows registration past a course's capacity. Commit with `fix: prevent duplicate registration` (or similar).",
        acceptanceCriteria: ["Bug is reproduced and fixed with a test or manual verification steps in the PR", "Commit message follows convention"],
      },
      {
        code: "GIT-005",
        title: "Resolve a Merge Conflict",
        description: "Intentionally create and resolve a merge conflict.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 8,
        estimatedHours: 1,
        instructions: "Create two branches editing the same lines of a file, merge one into main, then resolve the conflict when merging the second.",
        acceptanceCriteria: ["Conflict markers are fully resolved in the final commit", "Screenshot or description of the resolution included in the PR"],
      },
    ],
    researchQuestions: ["Merge vs Rebase — what's the difference and when would you use each?"],
    weeklyProjectTitle: "Team Ticket Simulation",
    weeklyProjectDescription: "Three simulated company tickets worked through proper feature-branch and PR workflow.",
    submissionRequirements: ["Pull request URL for each ticket"],
  },
  {
    weekNumber: 11,
    title: "Production Readiness",
    description: "Harden your application for production: security, testing, API documentation and deployment.",
    objectives: [
      "Apply core web security practices (CORS, Helmet, rate limiting, input validation)",
      "Write meaningful backend tests with Vitest and Supertest",
      "Document the API with Swagger/Postman",
      "Understand the deployment process for a full-stack app",
    ],
    topics: [
      "Security",
      "Validation",
      "CORS",
      "Helmet",
      "Rate Limiting",
      "Password Security",
      "JWT Security",
      "SQL Injection",
      "XSS",
      "Environment Variables",
      "Swagger",
      "Postman",
      "Vitest",
      "React Testing Library",
      "Supertest",
      "Deployment",
    ],
    resources: [
      {
        title: "OWASP Top Ten",
        description: "The most critical web application security risks.",
        url: "https://owasp.org/www-project-top-ten/",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 45,
        topic: "Security",
      },
      {
        title: "Vitest Documentation",
        description: "Official Vitest testing framework docs.",
        url: "https://vitest.dev/guide/",
        type: DOC,
        isRequired: true,
        estimatedMinutes: 45,
        topic: "Testing",
      },
    ],
    tasks: [
      {
        code: "PROD-001",
        title: "Harden the API",
        description: "Add Helmet, CORS and rate limiting to the backend from week 9.",
        type: TaskType.CODING,
        priority: TaskPriority.HIGH,
        difficulty: TaskDifficulty.MEDIUM,
        points: 10,
        estimatedHours: 1.5,
        instructions: "Add Helmet, a strict CORS origin allowlist, and rate limiting on the auth routes.",
        acceptanceCriteria: ["CORS rejects unexpected origins", "Auth endpoints are rate-limited"],
      },
      {
        code: "PROD-002",
        title: "Backend Test Suite",
        description: "Write the required backend test suite.",
        type: TaskType.CODING,
        priority: TaskPriority.URGENT,
        difficulty: TaskDifficulty.HARD,
        points: 20,
        estimatedHours: 3,
        instructions:
          "Using Vitest + Supertest, write tests for: login success, login failure, get courses, register course, duplicate registration rejected, full course rejected, admin creates course.",
        acceptanceCriteria: ["All 7 required scenarios are covered", "Tests run in CI (or documented to run locally) via `npm test`"],
      },
      {
        code: "PROD-003",
        title: "API Documentation",
        description: "Document the API with Swagger/OpenAPI.",
        type: TaskType.CODING,
        priority: TaskPriority.MEDIUM,
        difficulty: TaskDifficulty.MEDIUM,
        points: 8,
        estimatedHours: 1.5,
        instructions: "Add Swagger/OpenAPI annotations for at least 5 key endpoints, served at /api/docs.",
        acceptanceCriteria: ["/api/docs renders and lets you try at least one request", "Auth, request body and responses are documented"],
      },
    ],
    researchQuestions: ["Why should secrets like JWT_SECRET and DATABASE_URL live in environment variables instead of source code?"],
    weeklyProjectTitle: "Production Hardening Pass",
    weeklyProjectDescription: "Security middleware, a real test suite, and Swagger documentation added to the week 9 project.",
    submissionRequirements: ["Public GitHub repository URL", "Test output/coverage summary in the README"],
  },
  {
    weekNumber: 12,
    title: "Final Assessment",
    description: "Independently design and build a full-stack Project Management System from scratch.",
    objectives: [
      "Apply everything learned in the previous 11 weeks without step-by-step guidance",
      "Design your own data model, API and UI for a non-trivial domain",
      "Deliver a complete, working, independently-built application",
    ],
    topics: ["Independent Project Design", "Full-Stack Delivery"],
    resources: [
      {
        title: "Prisma Documentation",
        description: "Reference while designing the final schema.",
        url: "https://www.prisma.io/docs",
        type: DOC,
        isRequired: false,
        estimatedMinutes: 0,
        topic: "Reference",
      },
      {
        title: "React Documentation",
        description: "Reference while building the final UI.",
        url: "https://react.dev/learn",
        type: DOC,
        isRequired: false,
        estimatedMinutes: 0,
        topic: "Reference",
      },
    ],
    tasks: [
      {
        code: "FINAL-001",
        title: "Final Project: Project Management System",
        description: "Build a complete Project Management System independently.",
        type: TaskType.PROJECT,
        priority: TaskPriority.URGENT,
        difficulty: TaskDifficulty.HARD,
        points: 100,
        estimatedHours: 30,
        instructions:
          "Build a Project Management System with roles (Admin, Project Manager, Developer), Projects, Tasks, Members, Task Assignment, Status (TODO/IN_PROGRESS/REVIEW/DONE), Priority (LOW/MEDIUM/HIGH/URGENT), Due Dates, a Dashboard, Search, Filters and Pagination. This must be built independently, end-to-end (React + Express + Prisma + PostgreSQL).",
        acceptanceCriteria: [
          "All three roles exist with distinct permissions",
          "Tasks support status, priority, assignment and due dates",
          "Dashboard, search, filters and pagination are all implemented",
          "Deployed or runnable locally with clear setup instructions",
        ],
        isWeeklyProject: true,
      },
    ],
    researchQuestions: [],
    weeklyProjectTitle: "Project Management System",
    weeklyProjectDescription: "A full-stack Project Management System built independently, covering everything taught across the 12 weeks.",
    submissionRequirements: ["Public GitHub repository URL", "Live demo URL", "A short write-up of architectural decisions"],
  },
];
